import { createStyle } from "../../core/style";

export const row_auto = createStyle("grid-row", "auto");
export const row_span_1 = createStyle("grid-row", "span 1 / span 1");
export const row_span_2 = createStyle("grid-row", "span 2 / span 2");
export const row_span_3 = createStyle("grid-row", "span 3 / span 3");
export const row_span_4 = createStyle("grid-row", "span 4 / span 4");
export const row_span_5 = createStyle("grid-row", "span 5 / span 5");
export const row_span_6 = createStyle("grid-row", "span 6 / span 6");
export const row_span_full = createStyle("grid-row", "1 / -1");
export const row_start_1 = createStyle("grid-row-start", "1");
export const row_start_2 = createStyle("grid-row-start", "2");
export const row_start_3 = createStyle("grid-row-start", "3");
export const row_start_4 = createStyle("grid-row-start", "4");
export const row_start_5 = createStyle("grid-row-start", "5");
export const row_start_6 = createStyle("grid-row-start", "6");
export const row_start_7 = createStyle("grid-row-start", "7");
export const row_start_auto = createStyle("grid-row-start", "auto");
export const row_end_1 = createStyle("grid-row-end", "1");
export const row_end_2 = createStyle("grid-row-end", "2");
export const row_end_3 = createStyle("grid-row-end", "3");
export const row_end_4 = createStyle("grid-row-end", "4");
export const row_end_5 = createStyle("grid-row-end", "5");
export const row_end_6 = createStyle("grid-row-end", "6");
export const row_end_7 = createStyle("grid-row-end", "7");
export const row_end_auto = createStyle("grid-row-end", "auto");