name: \@tw-fns/react release

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/react/**"

permissions:
  contents: read
  id-token: write

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    if: ${{startsWith(github.event.head_commit.message, 'release(react):')}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10.23.0

      - name: CD to package directory
        run: cd packages/react

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish --no-git-checks --access public
