name: tw-fns release

on:
  push:
    branches:
      - "main"
    paths:
      - "packages/tw-fns/**"

permissions:
  contents: read
  id-token: write

jobs:
  test-build-publish:
    runs-on: ubuntu-latest
    if: ${{startsWith(github.event.head_commit.message, 'release(tw-fns):')}}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
        with:
          version: 10.23.0

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          cd packages/tw-fns
          pnpm build
          pnpm publish --no-git-checks --access public
